/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_db;

/**
 *
 * @author kyriacos2
 */
public class MainMenu extends javax.swing.JFrame {
    
    static Tables tablesForm;
    static Queries queriesForm;
    static Views viewsForm;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnTables = new javax.swing.JButton();
        jbtnQueries = new javax.swing.JButton();
        jbtnViews = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Car Rentals");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 240, 60));

        jbtnTables.setText("Tables");
        jbtnTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTablesActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTables, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, -1));

        jbtnQueries.setText("Queries");
        jbtnQueries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQueriesActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnQueries, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 150, -1));

        jbtnViews.setText("Views");
        jbtnViews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnViews, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, -1));

        setSize(new java.awt.Dimension(314, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTablesActionPerformed
        // TODO add your handling code here:
        tablesForm = new Tables();
        tablesForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnTablesActionPerformed

    private void jbtnQueriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQueriesActionPerformed
        // TODO add your handling code here:
        queriesForm = new Queries();
        queriesForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnQueriesActionPerformed

    private void jbtnViewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewsActionPerformed
        // TODO add your handling code here:
        viewsForm = new Views();
        viewsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnViewsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnQueries;
    private javax.swing.JButton jbtnTables;
    private javax.swing.JButton jbtnViews;
    // End of variables declaration//GEN-END:variables
}
