/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_db;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kyriacos2
 */
public class QrCustRentFreq extends javax.swing.JFrame {

    private Connection conn = null;
    private PreparedStatement prstmt = null;
    private ResultSet rs = null; 
    private String sql = "SELECT customer.Customer_ID, customer.First_Name, customer.Last_Name, COUNT(customer.Customer_ID) AS Times_Rent "
            + "FROM rents "
            + "INNER JOIN customer ON customer.Customer_ID = rents.Customer_ID "
            + "GROUP BY customer.Customer_ID "
            + "HAVING Times_Rent >= ? "
            + "ORDER BY Times_Rent DESC;";
    private int num=0;
    /**
     * Creates new form Query1
     */
    public QrCustRentFreq() {
        initComponents();
        conn=Utils.getConnection();
        Utils.clearTextBoxes(this);
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtNum = new javax.swing.JTextField();
        jbtnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("NUMBER OF RENTS PER CUSTOMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 730, 330));

        jLabel2.setText("Customers with rents equal or more than:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));

        jtxtNum.setText("jTextField1");
        getContentPane().add(jtxtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 80, 20));

        jbtnFind.setText("FIND");
        jbtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFindActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, 20));

        setSize(new java.awt.Dimension(801, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFindActionPerformed
        // TODO add your handling code here:
        if(jtxtNum.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter a number!");
        }
        else
        {
            num=Integer.parseInt(jtxtNum.getText());
            fillTableData();
        }
    }//GEN-LAST:event_jbtnFindActionPerformed

    @Override
    public void dispose(){
        try {
            if(conn!=null)
                conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(QrFindCustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainMenu.queriesForm.setVisible(true);
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QrCustRentFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QrCustRentFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QrCustRentFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QrCustRentFreq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QrCustRentFreq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnFind;
    private javax.swing.JTextField jtxtNum;
    // End of variables declaration//GEN-END:variables

    private void fillTableData() {
        try {
                prstmt=conn.prepareStatement(sql);
                prstmt.setInt(1,num);
                rs=prstmt.executeQuery();
                jTable.setAutoCreateRowSorter(true); ///////APORIA//////////
                Utils.showTable(rs, jTable);
                jTable.setDefaultEditor(Object.class,null);
            } catch (SQLException ex) {
                Logger.getLogger(QrService.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    if(prstmt!=null)
                        prstmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }
}
