/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_db;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kyriacos2
 */
public class QrFindCustomerInfo extends javax.swing.JFrame {
    
    private Connection conn = null;
    private PreparedStatement prstmt = null;
    private ResultSet rs = null; 
    private String sql;
    private String sql1 = " AND customer.Last_Name = ?;";

    /**
     * Creates new form Query1
     */
    public QrFindCustomerInfo() {
        initComponents();
        conn=Utils.getConnection();
        Utils.clearTextBoxes(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jbtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("FIND CUSTOMER INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 300, -1));

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        jtxtName.setText("jTextField1");
        getContentPane().add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 120, -1));

        jLabel3.setText("Surname:*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 20));

        jtxtSurname.setText("jTextField1");
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 120, -1));

        jLabel4.setText("*For Company customers let Surname field blank.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jbtnFind.setText("Find");
        jbtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFindActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 90, 840, 130));

        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        setSize(new java.awt.Dimension(923, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFindActionPerformed
        // TODO add your handling code here:
        sql="SELECT customer.First_Name, customer.Last_Name, customer.Street_Number As Street_Num, customer.Street, customer.City, customer.Postal_Code, customer.First_Registration "
            + "FROM customer "
            + "WHERE customer.First_Name = ?";
        if (jtxtSurname.getText().isEmpty())
                sql=sql+";";
            else
                sql=sql+sql1;
        try {
            prstmt=conn.prepareStatement(sql);
            try{
                if(jtxtName.getText().isEmpty())
                    throw new Exception();
                else
                    prstmt.setString(1,jtxtName.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"You must enter a name!");
                Logger.getLogger(QrFindCustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (!jtxtSurname.getText().isEmpty())
                prstmt.setString(2, jtxtSurname.getText());
            rs=prstmt.executeQuery();
            jTable.setAutoCreateRowSorter(true); ///////APORIA//////////
            Utils.showTable(rs, jTable);
            jTable.setDefaultEditor(Object.class,null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Gamiese");
            Logger.getLogger(TblReservations.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(prstmt!=null)
                    prstmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnFindActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        Utils.clearTextBoxes(this);
    }//GEN-LAST:event_jbtnClearActionPerformed

    @Override
    public void dispose(){
        try {
            if(conn!=null)
                conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(QrFindCustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainMenu.queriesForm.setVisible(true);
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QrFindCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QrFindCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QrFindCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QrFindCustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QrFindCustomerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnFind;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtSurname;
    // End of variables declaration//GEN-END:variables
}
