/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_db;

/**
 *
 * @author kyriacos2
 */
public class Tables extends javax.swing.JFrame {
    
    static TblReservations t1Form;
    static TblCustomers t2Form;
    static TblRentals t3Form;
    

    /**
     * Creates new form Tables
     */
    public Tables() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnTable1 = new javax.swing.JButton();
        jbtnTable2 = new javax.swing.JButton();
        jbtnTable3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tables");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("TABLES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jbtnTable1.setText("Reservations");
        jbtnTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTable1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 150, -1));

        jbtnTable2.setText("Customers");
        jbtnTable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTable2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, -1));

        jbtnTable3.setText("Rentals");
        jbtnTable3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTable3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, -1));

        setSize(new java.awt.Dimension(269, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnTable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTable2ActionPerformed
        // TODO add your handling code here:
        t2Form = new TblCustomers();
        t2Form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnTable2ActionPerformed

    private void jbtnTable3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTable3ActionPerformed
        // TODO add your handling code here:
        t3Form = new TblRentals();
        t3Form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnTable3ActionPerformed

    private void jbtnTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTable1ActionPerformed
        // TODO add your handling code here:
        t1Form = new TblReservations();
        t1Form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnTable1ActionPerformed

    @Override
    public void dispose(){
        Project_DB.mainForm.setVisible(true);
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnTable1;
    private javax.swing.JButton jbtnTable2;
    private javax.swing.JButton jbtnTable3;
    // End of variables declaration//GEN-END:variables
}
