/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_db;

import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author kyriacos2
 */
public class TblRentals extends javax.swing.JFrame {

   private Connection conn = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    private PreparedStatement prstmt = null;
    private final String sql="SELECT r.License_Plate, r.Start_Date, r.Finish_Date, r.Start_Location, r.Finish_Location, r.Return_State, r.Customer_ID, r.IRS_Number "
                             + "FROM rents AS r;";
    private String sqlins ="INSERT INTO rents (License_Plate, Start_Date, Finish_Date, Start_Location, Finish_Location, Return_State, Customer_ID, IRS_Number) "
                        + "VALUES(?,?,?,?,?,?,?,?);";
    private String sqlup ="UPDATE rents "
                        + "SET rents.Finish_Date=?, rents.Start_Location=?, rents.Finish_Location=?, rents.Return_State=?, rents.Customer_ID=?, rents.IRS_Number=? "
                        + "WHERE rents.License_Plate=? AND rents.Start_Date=?;";
    private String sqldl="DELETE FROM rents "
                        + "WHERE rents.License_Plate=? AND rents.Start_Date=?;";
    private String psqlins="INSERT INTO paymenttransaction (License_Plate, Start_Date, Payment_Amount, Payment_Method) "
                            + "VALUES (?,?,?,?);";
    private String psqldl="DELETE FROM paymenttransaction "
                        + "WHERE License_Plate=? AND Start_Date=?;";
    /**
     * Creates new form Table1
     */
    public TblRentals() {
        initComponents();
        conn = Utils.getConnection();
        prepareInputs();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtnInsert = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbCustomerID = new javax.swing.JComboBox<>();
        jdcEndDate = new com.toedter.calendar.JDateChooser();
        jdcStartDate = new com.toedter.calendar.JDateChooser();
        jtxtEndLocation = new javax.swing.JTextField();
        jtxtStartLocation = new javax.swing.JTextField();
        jcbLicensePlate = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jbtnEdit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxtReturn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbIRS = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtAmou = new javax.swing.JTextField();
        jcbMethod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 70, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 930, 400));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("RENTS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        jbtnInsert.setText("Insert");
        jbtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, -1));

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, -1));

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, -1));

        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 90, -1));

        jLabel2.setText("*License Plate:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel3.setText("*Start Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jLabel4.setText("*Start Location:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel5.setText("*Finish Location:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        jLabel6.setText("*Finish Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel8.setText("*Customer ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        jcbCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCustomerIDActionPerformed(evt);
            }
        });
        getContentPane().add(jcbCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, -1));

        jdcEndDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdcEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, 20));

        jdcStartDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdcStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, 20));

        jtxtEndLocation.setText("jTextField1");
        getContentPane().add(jtxtEndLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 120, 20));

        jtxtStartLocation.setText("jTextField1");
        getContentPane().add(jtxtStartLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, 20));

        jcbLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLicensePlateActionPerformed(evt);
            }
        });
        getContentPane().add(jcbLicensePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, -1));

        jLabel9.setText("*Mandatory fields");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jbtnEdit.setText("Edit Selected Row");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel10.setText("*Return State:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jtxtReturn.setText("jTextField1");
        getContentPane().add(jtxtReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 20));

        jLabel7.setText("*IRS Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        getContentPane().add(jcbIRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 180, -1));

        jLabel11.setText("*Payment Amount:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel12.setText("*Payment Method:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        jtxtAmou.setText("jTextField1");
        getContentPane().add(jtxtAmou, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 120, 20));

        jcbMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit Card", "Visa", "Bank Transfer", "Cash" }));
        jcbMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMethodActionPerformed(evt);
            }
        });
        getContentPane().add(jcbMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        setSize(new java.awt.Dimension(1264, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        Date StartDate,EndDate;
        
        StartDate=Date.valueOf(((JTextField)jdcStartDate.getDateEditor().getUiComponent()).getText());
        EndDate=Date.valueOf(((JTextField)jdcEndDate.getDateEditor().getUiComponent()).getText());
        
        if (jcbLicensePlate.getSelectedIndex()==-1 || jcbCustomerID.getSelectedIndex()==-1 || jtxtStartLocation.getText().isEmpty() || jtxtEndLocation.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please fill all mandatory fields!");
        }
        else
        {
            try {
                prstmt=conn.prepareStatement(sqlup);
                prstmt.setDate(1, EndDate);
                prstmt.setString(2, jtxtStartLocation.getText());
                prstmt.setString(3, jtxtEndLocation.getText());
                prstmt.setString(4, jtxtReturn.getText());
                prstmt.setInt(5,Integer.parseInt(jcbCustomerID.getSelectedItem().toString().split(", ")[0]));
                prstmt.setLong(6,Long.parseLong(jcbIRS.getSelectedItem().toString()));
                prstmt.setString(7, jcbLicensePlate.getSelectedItem().toString());
                prstmt.setDate(8, StartDate);
                
                int i=prstmt.executeUpdate();
                if(i==0)
                {
                   JOptionPane.showMessageDialog(null,"In order to change the rented vehicle or the start date of the rental\nthe current rent record must be deleted and a new one must be created!");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(QrService.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    if(prstmt!=null)
                        prstmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            fillTableData();
            clearInputs();
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jcbCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCustomerIDActionPerformed

    private void jcbLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbLicensePlateActionPerformed

    private void jbtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertActionPerformed
        // TODO add your handling code here:
        Date StartDate,EndDate;
        
        StartDate=Date.valueOf(((JTextField)jdcStartDate.getDateEditor().getUiComponent()).getText());
        EndDate=Date.valueOf(((JTextField)jdcEndDate.getDateEditor().getUiComponent()).getText());
        
        if (jcbLicensePlate.getSelectedIndex()==-1 || jcbCustomerID.getSelectedIndex()==-1 || jtxtStartLocation.getText().isEmpty() || jtxtEndLocation.getText().isEmpty() || jtxtAmou.getText().isEmpty() || jcbMethod.getSelectedIndex()==-1)
        {
            JOptionPane.showMessageDialog(null,"Please fill all mandatory fields!");
        }
        else
        {
            try {
                prstmt=conn.prepareStatement(sqlins);
                prstmt.setString(1, jcbLicensePlate.getSelectedItem().toString());
                prstmt.setDate(2, StartDate);
                prstmt.setDate(3, EndDate);
                prstmt.setString(4, jtxtStartLocation.getText());
                prstmt.setString(5, jtxtEndLocation.getText());
                prstmt.setString(6, jtxtReturn.getText());
                prstmt.setInt(7,Integer.parseInt(jcbCustomerID.getSelectedItem().toString().split(", ")[0]));
                prstmt.setLong(8, Long.parseLong(jcbIRS.getSelectedItem().toString()));
                
                prstmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(QrService.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    if(prstmt!=null)
                        prstmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                prstmt=conn.prepareStatement(psqlins);
                prstmt.setString(1, jcbLicensePlate.getSelectedItem().toString());
                prstmt.setDate(2, StartDate);
                prstmt.setFloat(3, (float) Double.parseDouble(jtxtAmou.getText()));
                prstmt.setString(4, jcbMethod.getSelectedItem().toString());
                
                prstmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(QrService.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    if(prstmt!=null)
                        prstmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            fillTableData();
            clearInputs();
        }
        
    }//GEN-LAST:event_jbtnInsertActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        clearInputs();
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        int i=jTable.getSelectedRow();
        if (i!=-1)
        {
            try {
                prstmt=conn.prepareStatement(sqldl);
                prstmt.setString(1, jTable.getModel().getValueAt(i, 0).toString());
                prstmt.setString(2, jTable.getModel().getValueAt(i, 1).toString());
                jTable.clearSelection();
                prstmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(QrService.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    if(prstmt!=null)
                        prstmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            fillTableData();
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a row!");
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
        int i=jTable.getSelectedRow();
        if (i!=-1)
        {
            jcbLicensePlate.setSelectedItem(jTable.getModel().getValueAt(i, 0).toString());
            jdcStartDate.setDate(Date.valueOf(jTable.getModel().getValueAt(i, 1).toString()));
            jdcEndDate.setDate(Date.valueOf(jTable.getModel().getValueAt(i, 2).toString()));
            jtxtStartLocation.setText(jTable.getModel().getValueAt(i, 3).toString());
            jtxtEndLocation.setText(jTable.getModel().getValueAt(i, 4).toString());
            jtxtReturn.setText(jTable.getModel().getValueAt(i, 5).toString());
            jcbCustomerID.setSelectedIndex(-1+Integer.parseInt(jTable.getModel().getValueAt(i, 6).toString()));
            jcbIRS.setSelectedItem(jTable.getModel().getValueAt(i, 7).toString());
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a row!");
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jcbMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMethodActionPerformed

    @Override
    public void dispose(){
        try {
            if(conn!=null)
                conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(QrFindCustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainMenu.tablesForm.setVisible(true);
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TblRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TblRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TblRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TblRentals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TblRentals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnInsert;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcbCustomerID;
    private javax.swing.JComboBox<String> jcbIRS;
    private javax.swing.JComboBox<String> jcbLicensePlate;
    private javax.swing.JComboBox<String> jcbMethod;
    private com.toedter.calendar.JDateChooser jdcEndDate;
    private com.toedter.calendar.JDateChooser jdcStartDate;
    private javax.swing.JTextField jtxtAmou;
    private javax.swing.JTextField jtxtEndLocation;
    private javax.swing.JTextField jtxtReturn;
    private javax.swing.JTextField jtxtStartLocation;
    // End of variables declaration//GEN-END:variables

    private void fillTableData() {
        try {
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
            jTable.setAutoCreateRowSorter(true); ///////APORIA//////////
            Utils.showTable(rs, jTable);
            jTable.setDefaultEditor(Object.class,null);
        } catch (SQLException ex) {
            Logger.getLogger(TblRentals.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(stmt!=null)
                    stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void prepareInputs() {
        try {
            stmt=conn.createStatement();
            rs=stmt.executeQuery("SELECT vehicles.License_Plate FROM vehicles;");
            while (rs.next())
            {
                jcbLicensePlate.addItem(rs.getString("License_Plate"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TblRentals.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(stmt!=null)
                    stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            stmt=conn.createStatement();
            rs=stmt.executeQuery("SELECT customer.Customer_ID, customer.First_Name, customer.Last_Name FROM customer;");
            while (rs.next())
            {
                jcbCustomerID.addItem(Integer.toString(rs.getInt("Customer_ID"))+", "+rs.getString("First_Name")+" "+rs.getString("Last_Name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TblRentals.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(stmt!=null)
                    stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            stmt=conn.createStatement();
            rs=stmt.executeQuery("SELECT e.IRS_Number FROM employee AS e;");
            while (rs.next())
            {
                jcbIRS.addItem(Integer.toString(rs.getInt("IRS_Number")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TblRentals.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(stmt!=null)
                    stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jdcStartDate.setDate(Date.valueOf(LocalDate.now()));
        jdcEndDate.setDate(Date.valueOf(LocalDate.now()));
        Utils.clearTextBoxes(this);
        Utils.clearComboBoxes(this);
    }

    private void clearInputs() {
        jdcStartDate.setDate(Date.valueOf(LocalDate.now()));
        jdcEndDate.setDate(Date.valueOf(LocalDate.now()));
        Utils.clearTextBoxes(this);
        Utils.clearComboBoxes(this);
        jTable.clearSelection();
    }
}
