/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_db;

import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author kyriacos2
 */
public class VwVehicleInfo extends javax.swing.JFrame {

   private Connection conn = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    private PreparedStatement prstmt = null;
    private final String sql="SELECT * FROM view1;";
    private String sqlup ="UPDATE view1 "
                        + "SET Damages=?, Malfunctions=?, Next_Service=?, Last_Service=?, Insurance_Exp_Date=?, Store_ID=? "
                        + "WHERE License_Plate=?;";
    /**
     * Creates new form Table1
     */
    public VwVehicleInfo() {
        initComponents();
        conn = Utils.getConnection();
        prepareInputs();
        fillTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbtnEdit = new javax.swing.JButton();
        jtxtPlate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtMalf = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtDamage = new javax.swing.JTextArea();
        jdcExp = new com.toedter.calendar.JDateChooser();
        jdcNext = new com.toedter.calendar.JDateChooser();
        jdcLast = new com.toedter.calendar.JDateChooser();
        jtxtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 70, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 910, 400));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("VEHICLE INFORMATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, -1));

        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 90, -1));

        jLabel2.setText("*License_Plate:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        jLabel3.setText("Damages:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 20));

        jLabel4.setText("*Next Service:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel5.setText("*Last Service:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));

        jLabel6.setText("Malfunctions:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jLabel7.setText("*Insurance Exp Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 20));

        jLabel8.setText("*Store ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 20));

        jLabel9.setText("*Mandatory fields");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jbtnEdit.setText("Edit Selected Row");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jtxtPlate.setText("jTextField1");
        getContentPane().add(jtxtPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 20));

        jtxtMalf.setColumns(20);
        jtxtMalf.setRows(5);
        jScrollPane2.setViewportView(jtxtMalf);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, 50));

        jtxtDamage.setColumns(20);
        jtxtDamage.setRows(5);
        jScrollPane3.setViewportView(jtxtDamage);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, 50));

        jdcExp.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdcExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, -1));

        jdcNext.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdcNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, -1));

        jdcLast.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jdcLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, -1));

        jtxtID.setText("jTextField2");
        getContentPane().add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, -1));

        setSize(new java.awt.Dimension(1231, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        boolean lathos=false;
        if (jtxtID.getText().isEmpty() || jtxtPlate.getText().isEmpty())
        {
            lathos=true;
            JOptionPane.showMessageDialog(null,"Please fill all mandatory fields!");
        }
        
        if(!lathos)
        {
            try {
                prstmt=conn.prepareStatement(sqlup);
                prstmt.setString(1, jtxtDamage.getText());
                prstmt.setString(2, jtxtMalf.getText());
                prstmt.setDate(3, Date.valueOf(((JTextField)jdcNext.getDateEditor().getUiComponent()).getText()));
                prstmt.setDate(4, Date.valueOf(((JTextField)jdcLast.getDateEditor().getUiComponent()).getText()));
                prstmt.setDate(5, Date.valueOf(((JTextField)jdcExp.getDateEditor().getUiComponent()).getText()));
                prstmt.setInt(6, Integer.parseInt(jtxtID.getText()));
                prstmt.setString(7, jtxtPlate.getText());
                
                prstmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(QrService.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    if(prstmt!=null)
                        prstmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            fillTableData();
            clearInputs();
        }
        
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        clearInputs();
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
        int i=jTable.getSelectedRow();
        if (i!=-1)
        {
            jtxtPlate.setText(jTable.getModel().getValueAt(i, 0).toString());
            jtxtDamage.setText(jTable.getModel().getValueAt(i, 1).toString());
            jtxtMalf.setText(jTable.getModel().getValueAt(i, 2).toString());
            jdcNext.setDate(Date.valueOf(jTable.getModel().getValueAt(i, 3).toString()));
            jdcLast.setDate(Date.valueOf(jTable.getModel().getValueAt(i, 4).toString()));
            jdcExp.setDate(Date.valueOf(jTable.getModel().getValueAt(i, 5).toString()));
            jtxtID.setText(jTable.getModel().getValueAt(i, 6).toString());
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a row!");
    }//GEN-LAST:event_jbtnEditActionPerformed

    @Override
    public void dispose(){
        try {
            if(conn!=null)
                conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(QrFindCustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainMenu.viewsForm.setVisible(true);
        super.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwVehicleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwVehicleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwVehicleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwVehicleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VwVehicleInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnUpdate;
    private com.toedter.calendar.JDateChooser jdcExp;
    private com.toedter.calendar.JDateChooser jdcLast;
    private com.toedter.calendar.JDateChooser jdcNext;
    private javax.swing.JTextArea jtxtDamage;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextArea jtxtMalf;
    private javax.swing.JTextField jtxtPlate;
    // End of variables declaration//GEN-END:variables

    private void fillTableData() {
        try {
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
            jTable.setAutoCreateRowSorter(true); ///////APORIA//////////
            Utils.showTable(rs, jTable);
            jTable.setDefaultEditor(Object.class,null);
        } catch (SQLException ex) {
            Logger.getLogger(VwVehicleInfo.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                if(stmt!=null)
                    stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(QrAvailVehYear.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void prepareInputs() {
        jdcNext.setDate(Date.valueOf(LocalDate.now()));
        jdcLast.setDate(Date.valueOf(LocalDate.now()));
        jdcExp.setDate(Date.valueOf(LocalDate.now()));
        Utils.clearTextBoxes(this);
        jtxtMalf.setText(null);
        jtxtDamage.setText(null);
    }

    private void clearInputs() {
        jdcNext.setDate(Date.valueOf(LocalDate.now()));
        jdcLast.setDate(Date.valueOf(LocalDate.now()));
        jdcExp.setDate(Date.valueOf(LocalDate.now()));
        Utils.clearTextBoxes(this);
        jTable.clearSelection();
        jtxtMalf.setText(null);
        jtxtDamage.setText(null);
    }
}
